### ISSUE TITLE
Use in server side

### ISSUE THREAD

**Issue by sungwoncho** [meteor-utilities/avatar#1]
I would like to use `{{> avatar }}` while rendering templates in the server side. I am using [meteor-handlebars-server](https://github.com/cmather/meteor-handlebars-server).

When I try to render `myTemplate.handlebars` with avatar partial, I get:

```
Error: The partial avatar could not be found
```

I tried to make `myTemplate.js` in the server directory like this:

``` javascript
Handlebars.templates.myTemplate({}, {
  avatar: Handlebars.templates.avatar
});
```

But it didn't do anything. Any suggestions?

**Comment by SachaG** [comment]
That may be an issue with the Avatar package: https://github.com/bengott/meteor-avatar

**Comment by sungwoncho** [comment]
Okay, I opened an issue there. Closing this.
