### ISSUE TITLE
Facebook image not showing

### ISSUE THREAD

**Issue by nicholasalanbrown** [meteor-utilities/avatar#18]
Hello:

I'm using the `accounts-facebook`` package for login and am successfully pulling back the Facebook services data, including`user.services.facebook.id`and storing it in the user document. However when I call`{{> avatar user=this shape="circle"}}``` in my template I just get an empty gray circle with no errors. Any ideas what the issue might be?

**Comment by aaronmyhre** [comment]
I have the same issue... were you able to resolve it?

**Comment by nicholasalanbrown** [comment]
I am still having this issue, which is a shame since it would be a really useful package. Anyone have any idea how to fix it?

**Comment by aaronmyhre** [comment]
Hey Nicholas -

It sounds like I had the same challenge as you a few weeks ago, but I haven't
been working on this lately so apologies if I put you in the wrong
direction.

My issue was that my template context was incorrect. This was corrected by
wrapping the avatar template with the following:

{{#with currentUser}}
    {{> avatar user=this shape="circle"}}
{{/with}}

**Comment by boblikesoup** [comment]
We have a userId stored in a notification and render it as so:
+avatar(userId=userId shape="circle")

It's weird because the Facebook avatars show up on every device (even iPhone browsers) except some iPhone apps.  Every other type of image works.  Have you tried different devices or avatars?

**Comment by timothyarmes** [comment]
PR received for this issue.

**Comment by boblikesoup** [comment]
It seems the error is because the image url stored in the database is being redirecting when it hits Facebook.
