### ISSUE TITLE
custom default image not working on live server

### ISSUE THREAD

**Issue by Pushplaybang** [meteor-utilities/avatar#19]
Hey There

we've loaded our app on a digital ocean box and it seems like the URL for default image is being escaped?

my options look like : 

``` js
Avatar.setOptions({
  fallbackType: 'default image',
  defaultImageUrl: "img/avatar-default.png",
  customImageProperty: 'profile.avatarUrl',
});
```

If I navigate to the url the image is loaded, but inspecting the source I get the following : 

``` bash
https://secure.gravatar.com/avatar/527aaddfcf91ca986f16b23dd4b2c80d?default=http%3A%2F%2Flocalhost%3A3000%2Fimg%2Favatar-default.png&size=200
```

any ideas?

**Comment by massimosgrelli** [comment]
I'm using something similar without the fallbackType field and it works on *.meteor.com

```
Avatar.setOptions({
  defaultImageUrl : "images/default-profile-pic.gif",
  backgroundColor : "#e8e8e8",
  customImageProperty : 'profile.avatarUrl',
});
```

PS: I can't make customImageProperty working instead. Does it work for you? I'm storing the URL in users.profile.avatarUrl field

**Comment by Pushplaybang** [comment]
interesting  - I'll give that a go.

PS:  haven't tested the custom image prop yet, another member of my team was implementing the upload so I'll have to check it out and report back.

**Comment by timothyarmes** [comment]
I believe that this is now fixed.

**Comment by Pushplaybang** [comment]
fantastic, I'll give it a crack.
