### ISSUE TITLE
Suggestion : optional CSS

### ISSUE THREAD

**Issue by Pushplaybang** [meteor-utilities/avatar#20]
the initial css is great for prototyping etc, but in a production app, I really rather this didn't stick its default styles in the header, would be great to be able to pass an option to turn it off.

**Comment by timothyarmes** [comment]
Hmm.

The styles aren't just the default ones; they're all required for the package to work properly. Also, since it's generated on the server the styles can be modified appropriately based on the options that have been set (colours etc.) so nothing needs to be overridden.

I don't see any advantage to having to copy them all manually into a static file. Perhaps I'm missing something?

**Comment by Pushplaybang** [comment]
Yeah  - on a big build I really don't want all of this injected into the head on my main html file, we painstakingly organise and optimise our CSS  / markup and assets, I doubt this is an issue for many people, but I'm sure I'm not working in the only team that would like complete control of this sort of thing, and I'd much rather commit it back than maintain a fork for a relatively simple option.

To my mind, if this interferes with it using a custom image set on the user doc, falling back to a social image, falling back to gravatar image and finally falling back to initials or a defined default image I'd agree with you,  - I understand that it might look broken if we disable this stuff, but thats the functionality I'm after from the package, and would much rather manage the styles with the rest of our assets.

**Comment by timothyarmes** [comment]
OK. Please make the minor change that I've noted in your pull request and I'll merge.

**Comment by Pushplaybang** [comment]
Thanks thats awesome, 

I've been away unfortunately due to a family tragedy, but I'm back in the mix now and have this on my list to get sorted asap, as we'd like it in our app thats launching in the next week.

P:)
