### ISSUE TITLE
How to use random bgColor for each user intials ?

### ISSUE THREAD

**Issue by guruganeshm** [meteor-utilities/avatar#24]
```
var customColorScheme = function (user) {
  if (user.profile.name === "Red")
    return "#ff0000";
   else if (user.profile.name === "Green")
     return "#00ff00";
   else
     return "#aaaaaa";
 };

   Avatar.setOptions({
   backgroundColor: customColorScheme,
  });
```

The above is not helping to set the random colors as mentioned in doc, 
what it does is it simply adds 

```
 backgroundColor:customColorScheme = function(user){if (user.profile.name === "Red")return"#ff0000";else if (user.profile.name === "Green")return "#00ff00";else return "#aaaaaa"; };" 
```

as string to the CSS Attribute. 

Am I doing this wrong ?? Please help!!  

I also tried randomColor js No results..

```
     var customColorScheme = function () {
       return randomColor();
     };

   Avatar.setOptions({
   backgroundColor: customColorScheme,
  });
```

**Comment by timothyarmes** [comment]
I'm on holiday at the moment, so I can't look into this right now. I'm wondering if the latest version's not yet been pushed to atmosphere - can you try using the latest code from this repository instead?

**Comment by raiyankamal** [comment]
@guruganeshm, can you check the export.js file in your avatar package? If you see something similar in the getBackgroundColor function, then you probably have the right version to make it work.

```
getBackgroundColor: function (user) {
    if (_.isString(Avatar.options.backgroundColor))
      return Avatar.options.backgroundColor;
    else if (_.isFunction(Avatar.options.backgroundColor))
      return Avatar.options.backgroundColor(user);
},
```

**Comment by guruganeshm** [comment]
@timothyarmes  @raiyankamal 

Thank you for the quick response, it was much helpful..
 cloned this repo and installed, worked like a magic.. :+1:

below is the random color generator I am using 

```
   var customColorScheme = function () {
   return randomColor();
 };

  Avatar.setOptions({
  backgroundColor: customColorScheme,
  });
```

**Comment by guruganeshm** [comment]
@timothyarmes  

Looking forward to latest version updated in atmosphere. That would be great!!
