### ISSUE TITLE
Avatars only render when I am logged in.

### ISSUE THREAD

**Issue by ghost** [meteor-utilities/avatar#28]
When I am logged in the users who have Gravatar email addresses show up as their gravatar. When I log out, they are replaced by the default icon? Any ideas?

**Comment by timothyarmes** [comment]
Hi,

The problem is probably that you're not publishing the user objects with enough information (either addresses or email hashes) when you're not logged in.

**Comment by ghost** [comment]
OK, that sounds sensible. I can use an email had from the UI helpers?

**Comment by ghost** [comment]
I see now, thank you. All clear in the docs.
