### ISSUE TITLE
Ghostery blocks avatar

### ISSUE THREAD

**Issue by brianlukoff** [meteor-utilities/avatar#29]
Ghostery is blocking Gravatar, and as a result the avatar package can't detect that no image is coming back and shows users that have Ghostery installed a broken image.

**Comment by timothyarmes** [comment]
I have Ghostery installed and I'm not seeing the problem, so it probably depends on your setting. 

In any case there's nothing that we can do if the user's blocking scripts that we need.

**Comment by brianlukoff** [comment]
Is there a way to disable checking Gravatar completely?

**Comment by timothyarmes** [comment]
I can't see how we can deal with this, so I'm closing it.
