### ISSUE TITLE
Avatar image as link

### ISSUE THREAD

**Issue by v3rron** [meteor-utilities/avatar#30]
It would be really nice to have an avatar image as link. For example, in application I'm working on, we need to be able to click on user avatar in order to go to his profile page. Is it currently possible?

**Comment by raiyankamal** [comment]
The Avatar package does not support this at the moment. The avatar package is only responsible for showing an user's avatar. Modifying the avatar package to put hyperlinks on avatars can violate the separation of concerns.
My suggestion would be to enclose the avatar in an hyperlink like so:`<a href='your_url_her'>{{>avatar}}</a>`

**Comment by timothyarmes** [comment]
Yes, just place your avatar in an `<a>`, there's no need for this package to do that for you.
