### ISSUE TITLE
Please update your instructions to clarify the need for properly publishing/subscribing to profile picture data

### ISSUE THREAD

**Issue by andersr** [meteor-utilities/avatar#36]
This package did not work properly for me until I added the folllowing. It was not clear to me from the instructions that there was a need to do this.  Before adding this, I was stuck with just displaying user initials, and was not aware the issue was tied to publish/subscribe.
### Client-side:

```
Meteor.subscribe('userData');
```
### Server-side (in my case, for login via Facebook/Google):

```
Meteor.publish("userData", function () {
  if (this.userId) {
    return Meteor.users.find( {_id: this.userId},
      {fields: 
        {
          "services.google.picture": true,
          "services.google.name": true,
          "services.facebook.id": true,
          "services.facebook.name": true
        }
      });
  } else {
    this.ready();
  }
});
```

Please consider updating the instructions to clarify the need for proper publish/subscribe. (Or perhaps simply have the package itself add these publish/subscribe code snippets?)

**Comment by asidiali** [comment]
Agreed. It's not immediately clear that you have to make sure you're publishing the correct data. I assumed the package would do that itself. Thanks for the nice example!

**Comment by SachaG** [comment]
Good point, just added a note about this.
