### ISSUE TITLE
put avatar in the same line

### ISSUE THREAD

**Issue by leizard** [meteor-utilities/avatar#46]
I have a array of user ID and want to set a line of avatar base on this array. So I use

```
        {{#each userIDs}}
            <span>{{> avatar userId=this size="small"}}</span>
        {{/each}}
```

But the avatars stack vertically. Can someone help me ? 
Thank you

**Comment by timothyarmes** [comment]
Hi,

Try styling your span as an inline block or a float.

**Comment by leizard** [comment]
Hi, sorry. I tried this

```
    <div class="col-sm-12">
            {{#each userIDs}}
                <span style="display: inline">{{> avatar userId=this size="small"}}</span>
            {{/each}}
    </div>
```

But still doesn't work

**Comment by leizard** [comment]
oh never mind. Just because i'm stupid. I use display: inline-block and work like charm. thank you very much
