### ISSUE TITLE
Setting generateCSS to false has no effect

### ISSUE THREAD

**Issue by jorisroling** [meteor-utilities/avatar#47]
The option **generateCSS** has no effect because, on initial load, **Avatar.setOptions({});** is called, and default value of **generateCSS** is **true**. And the injection has already taken place, before anyone could set **generateCSS** to **false**. What to do?

**Comment by adamgins** [comment]
Hi, was this resolved? We need to ensure `<meta http-equiv="X-UA-Compatible" content="IE=edge">` is the first thing in our HTML head or things get broken on IE. Is there someway to disable the CSS that Avatar is inserting above everything else?

For example:

```
<!DOCTYPE html>
<html>
<head>
<style>.avatar { 
      height: 50px; 
      width: 50px; 
      position: relative; 
    } 
.avatar .avatar-image, 
.avatar .avatar-initials { 
      height: 100%; 
      width: 100%; 
      position: absolute; 
      top: 0px; 
      left: 0px; 
    } 
.avatar .avatar-image { 
      z-index: 10; 
      background-color: #fff; 
    } 
.avatar .avatar-initials { 
      display: block; 
      background-size: 100% 100%; 
      background-color: #aaa; 
      color: #fff; 
      font-size: 25px; 
      line-height: 50px; 
      font-family: "Helvetica Neue", Helvetica, "Hiragino Sans GB", Arial, sans-serif; 
      text-align: center; 
      z-index: 1; 
    } 
.avatar-rounded .avatar-image, 
.avatar-rounded .avatar-initials { 
      border-radius: 5px; 
    } 
.avatar-circle .avatar-image, 
.avatar-circle .avatar-initials { 
      border-radius: 50%; 
    } 
.avatar-hide-image .avatar-image { 
      display: none; 
    } 
.avatar-hide-initials .avatar-initials { 
      display: none; 
    } 
  .avatar-large {width: 80px; min-width: 80px; height: 80px;}
.avatar-large .avatar-initials {font-size: 40px; line-height: 80px;}
.avatar-small {width: 30px; min-width: 30px; height: 30px;}
.avatar-small .avatar-initials {font-size: 15px; line-height: 30px;}
.avatar-extra-small {width: 20px; min-width: 20px; height: 20px;}
.avatar-extra-small .avatar-initials {font-size: 10px; line-height: 20px;}
</style>
<meta http-equiv="X-UA-Compatible" content="IE=edge">

```

Note we are using meteorhacks inject to `Inject.rawHead('my-meta',
    '<meta http-equiv="X-UA-Compatible" content="IE=edge">');`

see https://atmospherejs.com/meteorhacks/inject-initial

@dave-buzzy FYI

**Comment by dave-buzzy** [comment]
+1

**Comment by adamgins** [comment]
@jorisroling @subosito wondering if you have any input here pls?

**Comment by adamgins** [comment]
What about changing https://github.com/meteor-utilities/avatar/blob/e67a2173816b82c361948f59e833ecf6beda5694/export.js#L194 to `Avatar.setOptions({generateCSS:false});` by default as @jorisroling says, it's too late after that point as the CSS is already in the <head>?

**Comment by subosito** [comment]
@adamgins @jorisroling I think moving `createCSS` call to `Meteor.startup` block did the trick. You can see here https://github.com/subosito/avatar/commit/268da5fbf0ca723d9e1a6133fea861325f37ab9b.

What do you guys think? Is it ok to create a PR for this?
