### ISSUE TITLE
Exception in template helper: TypeError: Cannot read property 'undefined' of undefined

### ISSUE THREAD

**Issue by quape** [meteor-utilities/avatar#49]
Just did this (@0.9.2):
`{{> avatar user=user shape="circle"}}`

gravatar image is displayed but log reported:

```
Exception in template helper: TypeError: Cannot read property 'undefined' of undefined
  at sizeClass (254:35)
  at Object.Template.avatar.helpers.size (89:12)
  ...
```

**Comment by meteorimpact** [comment]
You're probably setting the Avatar options directly instead of using the setOptions() method.

**Comment by quape** [comment]
Genius!
I came from the old bengott:avatar and didn't see that to change.
