### ISSUE TITLE
Export Gravatar or write proxy method (for Gravatar.hash()) to use emailHashProperty

### ISSUE THREAD

**Issue by yoh** [meteor-utilities/avatar#6]
Hi !

I would to use `emailHashProperty` to be able to show avatars without publish users emails.
I try to set a `profile.emailHash` property on user when it is saved but I can't access to `Gravatar` to use `Gravatar.hash()` method.
Is there way to do this with this package (through this package) or must I add `jparker:gravatar` on my project to use `Gravatar.hash()` ?

Is it intelligent to export `Gravatar` object or add a proxy method on `Avatar` to use `Gravatar.hash()` ?

**Comment by timothyarmes** [comment]
Hi,

Why do you need to access Gravatar.hash()?

If you've set the `profile.emailHash` property and your user object has this property set on it, then the hash will be used automatically by this package.

**Comment by yoh** [comment]
Yes, but to set `emailHash`on my user object, I need to hash his email address with a hash function.
This function is accessible on `Gravatar`object (`Gravatar.hash(emailAddress)`).

On my app, I need to add `jparker:gravatar` package (same used by `utilities:avatar`) to use `Gravatar.hash(emailAddress)` function when the user is saved.

Example : 

```
Accounts.onCreateUser(function(options, user) {
    if (user.services) {
        if (user.services.password){
            user.profile = options.profile;
            user.profile.emailHash = Gravatar.hash(options.email);
        }
    }

    return user;
});

```

How do you calculate the `emailHash` in your app ?
I think `utilities:avatar` must export this feature.

**Comment by timothyarmes** [comment]
Ah, I see.

I currently do this:

```
hash = CryptoJS.MD5(email.address.trim().toLowerCase()).toString()
doc.emailHash = hash
```

However, since Gravatar is already used by this package it does make sense to provide a direct access to that function.

**Comment by yoh** [comment]
Yes, perhaps a day, Gravatar not just hash email with md5 algo but with another algorithm.

I think apps don't have to know which algorithm must be used, but avatar package must  provide method to do this.

I see two ways to do :  
1) add method on exported var `Avatar` to proxy `Gravatar.hash()` method
2) add method on exported var `Avatar` to provide `Gravatar`object

Do you want I create a PR for 1) or 2) ?

**Comment by timothyarmes** [comment]
Sure. I prefer 1).

**Comment by yoh** [comment]
PR for 1) : https://github.com/meteor-utilities/avatar/pull/7

**Comment by timothyarmes** [comment]
I've added this feature. Thanks.
