### ISSUE TITLE
Suggestion to update your Guide

### ISSUE THREAD

**Issue by juliomac** [meteor-utilities/avatar#66]
Nice package! Thanks!!!

One good tip to add in your Documentation is to have the following Data context when the Avatar does not show. 

```{{#with currentUser}}

  <p>{{> avatar user=this shape="circle"}}</p>

{{/with}}```

**Comment by timothyarmes** [comment]
That's overly complicated. Just:

```
{{> avatar user=currentUser shape="circle"}}
```

And I think that's obvious from the guide!

**Comment by juliomac** [comment]
This is what helped me:
https://forums.meteor.com/t/solved-user-avatar-not-displaying/6383

**Comment by juliomac** [comment]
You're right. You can close this.
